### ISSUE TITLE
build: ship commonjs version for node and testing

### ISSUE THREAD

**Issue by Hotell** [abraham/reflection#10]
Currently if i wanna use same polyfills in testing environment ( jest ) like in dev/prod with typescript I have to do a lot of ceremony:

- in jest config 
```js
{
transformIgnorePatterns: [
    '<rootDir>/node_modules/(?!@abraham/reflection/.*)',
  ],
}
```
- in tsconfig
```json
{
"allowJs": true
}
```

this is rather hack then good DX experience :)

shipping commonJS bundle is a no brainer and would help a lot ;) cheers

**Comment by abraham** [comment]
Are you compiling to JS and then running the tests on the compiled version?

How would you imagine the two build targets would be handled? Something like this? 

```ts
import '@abraham/reflection';
```
```js
require('@abraham/reflection/dist/common.js');
```

**Comment by Hotell** [comment]
the API should remain same, package.json should be source of truth here., I think. WDYT ? :)

```json
{
  "main": "dist/reflection.umd.js", // commonjs bundle
  "module": "dist/index.js", // es2015 module
}
```

**Comment by abraham** [comment]
Are there build tools that use the `module` entry? I think unpkg does but I don't know about any others.

**Comment by Hotell** [comment]
Webpack, rollup ... I'm using it all the time https://github.com/Hotell/typescript-lib-starter

**Comment by Hotell** [comment]
that works! although rollup consumes es2015 module files 😥so there is no dist/index.js anymore

![image](https://user-images.githubusercontent.com/1223799/43230294-045bcc6e-9068-11e8-9a1d-f488981c6009.png)

**Comment by Hotell** [comment]
oh nevermind, it builds correctly when explicitly running build within node modules :) 
![image](https://user-images.githubusercontent.com/1223799/43230398-6009ab1c-9068-11e8-9505-4335587c2053.png)
