### ISSUE TITLE
error TS2339: Property 'getMetadata' does not exist on type 'typeof Reflect'

### ISSUE THREAD

**Issue by ova2** [abraham/reflection#17]
Thanks for your reflection lib. I have tried it in my playground project as drop-in replacement for reflect-metadata, but I get the error:

 **error TS2339: Property 'getMetadata' does not exist on type 'typeof Reflect'**

Project: https://github.com/ova2/frontend-tooling-tutorial/tree/master/typescript-playground/dependency-injection-container

**Steps to reproduce:**
1) Clone the project https://github.com/ova2/frontend-tooling-tutorial
2) Go to typescript-playground/dependency-injection-container
2) Remove reflect-metadata from package.json and run "npm install"
3) npm install @abraham/reflection
4)  Replace import 'reflect-metadata' by import '@abraham/reflection' in di-container.ts
5) Run "npm run test" -> error

You will also see the error in your IDE because the proper getMetadata() is not found. Furthermore, I think the return value of this method in your TS definition file should be "any". This is the type in reflect-metadata.

**Comment by abraham** [comment]
Thanks for the detailed steps. I'll try to take a look soon.
