### ISSUE TITLE
Syntax error—IE11 support?

### ISSUE THREAD

**Issue by adamdport** [abraham/reflection#177]
I quickly discovered that [you use lamda functions](https://github.com/abraham/reflection/blob/master/src/index.ts#L63). They blow up in IE11. I couldn't find any documentation staying what your intentions for this library were. Can you (at least) add a note to your readme about what browsers are supported? Thanks.

**Comment by davidstellini** [comment]
First of all, great work. I was wondering if running babel or some sort of transpile to ES5 after the library is built, and packaging it up as a separate bundle? It can all be done via an npm script. However I'm wondering if it would drastically increase build size.

**Comment by abraham** [comment]
I don't plan on creating multiple builds of Reflection. I want there to be a single modern build that targets a specific ES year and users will have to polyfill/transpile that for their specific needs.
