### ISSUE TITLE
circular references are not working

### ISSUE THREAD

**Issue by syffs** [abraham/reflection#198]
According to my testing, circular references are not working, just like reflect-metadata (typescript seems to be the [root cause](https://github.com/microsoft/TypeScript/issues/4521)). 

It'd need a workaround to be supported... AFAIK, Angular uses forward refs

**Comment by abraham** [comment]
My reading of the issue you linked to (and it's linked issues) this is more of a TypeScript problem then a problem with this library? Is that correct? Or do you have suggestions of changes that can be made in this library to help resolve the problem?

**Comment by abraham** [comment]
Happy to make changes but I'd need more details on what the issue is.
