### ISSUE TITLE
feat: add getOwnMetadata

### ISSUE THREAD

**Issue by Hotell** [abraham/reflection#3]
To be able to use this smaller Reflect polyfill in real apps ( primarily powered by [injection-js](https://github.com/mgechev/injection-js) ),  `getOwnMetadata` API is required

**Current Behaviour:**

![image](https://user-images.githubusercontent.com/1223799/43135881-470d43f2-8f47-11e8-81d7-30a0418f502e.png)
![image](https://user-images.githubusercontent.com/1223799/43135891-518f4a5a-8f47-11e8-97a8-8fc2fd43c1d6.png)

**Comment by abraham** [comment]
Fixed in #4
