### ISSUE TITLE
bug: reflection doesn't work with param decorators

### ISSUE THREAD

**Issue by Hotell** [abraham/reflection#6]
after #3 was closed, injection-js will pass although app will error out.
Everything is annotated properly ( I have tests for it and it works with reflect-metadata )

Issue might be with injecting non Class references via `@Inject()` param decorator. Just shooting in the dark here...

![image](https://user-images.githubusercontent.com/1223799/43147631-cd870d34-8f63-11e8-95eb-f7d91c68e3a6.png)

axios-http source:

https://github.com/Hotell/axios-http/blob/master/src/interceptor.ts#L49-L52

You can test it here:

https://codesandbox.io/s/6zx71n084n

**Comment by abraham** [comment]
Fix in v0.3.0

**Comment by Hotell** [comment]
gonna test it ASAP ! keep rockin @abraham 💪

**Comment by abraham** [comment]
Note that `/dist/reflect` is now removed so you just use the main entry. `import '@abraham/reflection`.

**Comment by Hotell** [comment]
and we have a winner ;) thanks for prompt fixes dude !

![image](https://user-images.githubusercontent.com/1223799/43165887-5b095014-8f95-11e8-9b2a-1fec35624969.png)

**Comment by abraham** [comment]
Nice!

**Comment by Hotell** [comment]
**Before:**

![image](https://user-images.githubusercontent.com/1223799/43166180-2d62750e-8f96-11e8-9e45-7cba575168cb.png)

**After:**

![image](https://user-images.githubusercontent.com/1223799/43166256-5e5e6974-8f96-11e8-8728-d52cbcd3167a.png)


👌👌👌👌👌👌👌👌👌👌👌👌👌👌👌👌👌👌👌👌👌👌👌👌👌👌👌

**Comment by abraham** [comment]
![giphy](https://user-images.githubusercontent.com/3341/43166718-ef4ca926-8f5c-11e8-8f0b-6bb106fba3e1.gif)

**Comment by Hotell** [comment]
Interesting, on [codesandbox it still doesn't work](https://codesandbox.io/s/github/Hotell/axios-http/tree/master/examples/swapi-people-app) :-/ but [locally all good ](https://github.com/Hotell/axios-http/tree/master/examples/swapi-people-app)

**Comment by Hotell** [comment]
https://github.com/CompuIves/codesandbox-client/issues/1004

**Comment by abraham** [comment]
Interesting.
