### ISSUE TITLE
This package is somehow disturbing monaco editor? - Uncaught TypeError: Cannot read property 'value' of undefined at decorators.ts

### ISSUE THREAD

**Issue by softmarshmallow** [abraham/reflection#630]
This is just a hypothesis. I'm here to ask the author if this is a valid theory.
https://github.com/suren-atoyan/monaco-react/issues/237

1. The monaco react is using monaco internally.
2. the project [designto-code](https://github.com/bridgedxyz/designto-code) is using monaco react and [flutter-builder](https://github.com/bridgedxyz/flutter-builder).
3. flutter-builder uses `abraham/reflection` for custom decorator. the issue is caused from `decorators.ts:12`

I'm not sure if monaco is crashing reflection or reflection is crashing monaco

![image](https://user-images.githubusercontent.com/16307013/120513707-7fa0ec80-c407-11eb-9e7a-12eb5b0d2fbb.png)

As an expert, author of this library, please share your thoughts!

**Comment by abraham** [comment]
It looks like the code doesn't account for the possibility of `descriptor` being undefined. Are you sure it should always have a value?

**Comment by softmarshmallow** [comment]
```
export function ignore(): (target: object, propertyKey: string) => void {
    return registerIgnoreFieldProperty;
}

export function defaultParam(): (target: object, propertyKey: string) => void {
    return registerDefaultParamProperty;
}
```

I have these two decorator, and both are just simple annotation that does not take any as input.

Usage
```
@ignore
fieldA: number

@defaultParam()
fieldA: number
```



Full code
```
export const paramMetadataKey = Symbol("param");
import { Reflection as Reflect } from '@abraham/reflection';

export function param(props?: {
    name?: string,
    default?: boolean
}) {
    return Reflect.metadata(paramMetadataKey, props.name);
}

//#region default param
export function defaultParam(): (target: object, propertyKey: string) => void {
    return registerDefaultParamProperty;
}

function registerDefaultParamProperty(target: object, propertyKey: string): void {
    let properties: string[] = Reflect.getMetadata(paramMetadataKey, target);

    if (properties) {
        properties.push(propertyKey);
    } else {
        properties = [propertyKey];
        Reflect.defineMetadata(paramMetadataKey, properties, target);
    }
}

export function getDefaultParamProperties(origin: object): object {
    const properties: string[] = Reflect.getMetadata(paramMetadataKey, origin);
    const result = {};
    properties.forEach(key => result[key] = origin[key]);
    return result;
}

//#endregion



//#region ignore


export const ignoreMetadataKey = Symbol("param");

export function ignore(): (target: object, propertyKey: string) => void {
    return registerIgnoreFieldProperty;
}

function registerIgnoreFieldProperty(target: object, propertyKey: string): void {
    let properties: string[] = Reflect.getMetadata(ignoreMetadataKey, target);

    if (properties) {
        properties.push(propertyKey);
    } else {
        properties = [propertyKey];
        Reflect.defineMetadata(ignoreMetadataKey, properties, target);
    }
}

export function getIgnoreProperties(origin: object): object {
    const properties: string[] = Reflect.getMetadata(ignoreMetadataKey, origin);
    const result = {};
    properties.forEach(key => result[key] = origin[key]);
    return result;
}

//#endregion
```


Do you see the problem?

**Comment by softmarshmallow** [comment]
And also what are your thoughts on https://github.com/suren-atoyan/monaco-react/issues/237#issuecomment-854207073 ?

**Comment by tripodsgames** [comment]
> And also what are your thoughts on [suren-atoyan/monaco-react#237 (comment)](https://github.com/suren-atoyan/monaco-react/issues/237#issuecomment-854207073) ?

Sorry, i was wrong in that comment.

As @abraham says, your `descriptor` is probably optional.
So instead of using

```typescript
typeof descriptor.value === 'function'
typeof descriptor.get ===  'function'
```
Use
```typescript
typeof descriptor?.value === 'function'
typeof descriptor?.get ===  'function'
```

**Comment by softmarshmallow** [comment]
Hi. @tripodsgames  What part (line) of the code are you referencing?

**Comment by tripodsgames** [comment]
> Hi. @tripodsgames What part (line) of the code are you referencing?

The if inside the memoize function

```typescript
if(typeof descriptor.value === 'function'){
    ...
}else if(typeof descriptor.get ===  'function'){
    ...
}
```

**Comment by softmarshmallow** [comment]
> > Hi. @tripodsgames What part (line) of the code are you referencing?
> 
> The if inside the memoize function
> 
> ```ts
> if(typeof descriptor.value === 'function'){
>     ...
> }else if(typeof descriptor.get ===  'function'){
>     ...
> }
> ```

I'me sorrt i still don't get it.

Which part exactly? where is that code coming from? Can you give us the link

I cannot find that code snippet neither on flutter-builder(using package) or reflection(this package)

**Comment by tripodsgames** [comment]
> > > Hi. @tripodsgames What part (line) of the code are you referencing?
> > 
> > 
> > The if inside the memoize function
> > ```ts
> > if(typeof descriptor.value === 'function'){
> >     ...
> > }else if(typeof descriptor.get ===  'function'){
> >     ...
> > }
> > ```
> 
> I'me sorrt i still don't get it.
> 
> Which part exactly? where is that code coming from? Can you give us the link
> 
> I cannot find that code snippet neither on flutter-builder(using package) or reflection(this package)

Oh, I found the file `decorators.ts` in vscode repository.

https://github.com/microsoft/vscode/blob/85bf591c5879a4f827a730ea41667f1560ef1017/src/vs/base/common/decorators.ts#L31

**Comment by abraham** [comment]
I'd think it's unlikely that this package would break VS Code.

Please link to a repository and simple steps to reproduce the error.

**Comment by softmarshmallow** [comment]
Hi. 

Details are listed at below comment
https://github.com/suren-atoyan/monaco-react/issues/237#issuecomment-853145772

yarn && yarn editor
visit localhost:3000/figma/to-react -> works
visit localhost:3000/figma/to-flutter -> breaks

**Comment by softmarshmallow** [comment]
Here's the reply from monaco team
https://github.com/microsoft/monaco-editor/issues/2522#issuecomment-859342153

Are you able to take a look into any malicious part that could cause this error? @abraham

**Comment by tripodsgames** [comment]
> And also what are your thoughts on [suren-atoyan/monaco-react#237 (comment)](https://github.com/suren-atoyan/monaco-react/issues/237#issuecomment-854207073) ?

#605 is the same error.

**Comment by softmarshmallow** [comment]
Can I get an update for this?

**Comment by abraham** [comment]
Have you tried the latest version as @tripodsgames suggested? https://github.com/suren-atoyan/monaco-react/issues/237#issuecomment-854207073

**Comment by abraham** [comment]
It seems like the issue is with another project and not this library.
