### ISSUE TITLE
Cannot use with Electron

### ISSUE THREAD

**Issue by roddc** [abraham/reflection#731]
I got an error saying:
`Error [ERR_REQUIRE_ESM]: require() of ES Module D:\ws\terminal\node_modules\@abraham\reflection\dist\index.umd.js from D:\ws\terminal\packages\main\dist\index.cjs not supported.
index.umd.js is treated as an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which declares all .js files in that package scope as ES modules.
Instead rename index.umd.js to end in .cjs, change the requiring code to use dynamic import() which is available in all CommonJS modules, or change "type": "module" to "type": "commonjs" in D:\ws\terminal\node_modules\@abraham\reflection\package.json to treat all .js files as CommonJS (using .mjs for all ES modules instead).`
Because Electron doesn't support ES Modules for now, I have to manually change the `index.umd.js` to `index.cjs` to make it work. Is there any solutions?

**Comment by abraham** [comment]
This should be fixed with v0.12
